### ISSUE TITLE
Great deskclock, timer!! Missing connection to file manager for selection of alarm sound

### ISSUE THREAD

**Issue by gilunixuser** [qw123wh/Aospdeskclock#10]
Hi your deskclock / timer is excellent. I have installed it on my android from f-droid.
It is a petty that is quite hard to find your app even within f-droid.

I have thousands of songs on my mobile. Thus a very important function I am really missing is to be able easily to select a song for alarm by first selecting an existing file manager and than selecting the song file via the file manager.
This feature would make it much much easier than running through the existing selection for finding the needed song for alarm.

It would be great if you can implement this feature.
Best Regards!

**Comment by qw123wh** [comment]
It can already be done.  There are two ways to do this. First method in settings select sounds and then default alarm sound and choose ringtone from file manager.  Second method open the application click on the alarm ringtone, then at the top in personal sounds click on add new and the file manager opens

**Comment by gilunixuser** [comment]
According to f-droid I am using version 1.2.1. - German translation.
In settings --> Timer --> timer sound --> I can add a sound. There only opens a list of all sounds but I wouldn't call it a file manager, because it is very rudimentary and very difficult to find the needed song file. 
My approach would be that you can select first a professional file manager installed. Within the prof. file manager you easily can select what you need.

**Comment by qw123wh** [comment]
https://user-images.githubusercontent.com/59417474/135064847-61b6a07f-d151-4158-9b6e-e8651207d257.MOV

As you can see from this screen record you can open the file manager and then search in the file manager, then once in the file manager you have to select the desired ringtone.  It is pretty much the same thing that happens in google clock.

**Comment by gilunixuser** [comment]
Thanks for your answer. Actually I figured out now, that I hadn't activated "show extended devices" in settings of your file manager. This I was looking for. Maybe you should activate it by standard and make this setting more obvious instead of hided. Or maybe easier you take out these settings complety and have shown SD-Card and internal memory including size always by default.
Something else, if I click on your file manager on "Audio", "recent" or "downlaods" than the search function for a file is not available anymore. It is only visible within SD-Card and internal memory. It should be seen on all views, isn't it?

**Comment by qw123wh** [comment]
The file manager is the default and pre-installed on android, my clock app has nothing to do with the file manager, they are two different apps, the clock app opens a link with the default file manager.  More like a problem with the file manager

**Comment by gilunixuser** [comment]
I see! Thanks!
