### ISSUE TITLE
[Feature request] Option to disable 'next alarm' notification

### ISSUE THREAD

**Issue by woj-tek** [qw123wh/Aospdeskclock#20]
Would it be possible to add option to disable "next alarm" notification? Or add it as notification category like in main google/samsung clock app?

**Comment by qw123wh** [comment]
This version is old, there are two more recent versions.  The first, most recent version with material design is also found on fdroid
https://github.com/qw123wh/new-clock-fdroid

the other version with material you is still under development but works well.  
https://github.com/qw123wh/new-clock

In these two it is possible in the settings to disable these notifications at the system level

**Comment by woj-tek** [comment]
I already switched to [new-clock-fdroid](https://github.com/qw123wh/new-clock-fdroid) recently and indeed it has the option
