### ISSUE TITLE
AOSP Calculator

### ISSUE THREAD

**Issue by Pranab009** [qw123wh/Aospdeskclock#6]
Sir please build an AOSP Calculator app with some extra features like
Tiles button, pop-up or floating Calculator.
Please sir think about it your desk clock is too good.

**Comment by qw123wh** [comment]
I can also bring the aosp calculator, but it has a bug. The bug is the following clicking on the operation history nothing happens.
I don't know how to fix this bug. If you want I can build aosp calculator but know it has this bug

**Comment by darnrain** [comment]
I know your looking for an AOSP calculator but I use Simple Calculator on google play store. It's free no ads.

https://play.google.com/store/apps/details?id=com.sawicki.piotr.calculator.simple.simplecalculator&hl=en_US&gl=US

**Comment by qw123wh** [comment]
The best beautiful calculator, no ads, no permission is the oneplus calculator.
This https://www.apkmirror.com/apk/oneplus-ltd/oneplus-calculator/oneplus-calculator-2-0-0-210322213558-10f33ee-release/
try to see if it installs, on my phone with aosp rom it works

**Comment by Pranab009** [comment]
I throughout that every app has some bugs.
And "history" is not big issue.
You published your app and fix bugs
in near future.Totally bugs free app is not possible.work on it.👍

**Comment by qw123wh** [comment]
@Pranab009 here's the calculator https://github.com/qw123wh/Aosp-Calulator/tree/0.1
Start trying it then calmly I'll put it on android and fix something if I can.
I have released a trial apk
