### ISSUE TITLE
Great Alarm clock

### ISSUE THREAD

**Issue by darnrain** [qw123wh/Aospdeskclock#7]
Just wanted to let you know this is a wonderful Alarm clock, thank you so much for maintaining it. 

Some changes that would be cool.

1. The ability to change the background and font color.

2. Set timer expiration after X minutes. I don't know many times I set a timer and went outside only to come back in and find my my phone has been going off for 60 minutes.

**Comment by qw123wh** [comment]
I'm glad you like it, I didn't quite understand the timer problem.
The color can be changed but I don't know how to create an option to make it change for the user.  What colors would you like?

**Comment by darnrain** [comment]
You know how the alarm will Silence after 10 minutes? I wish the timer had the same option. That way if I am not around and the timer goes off it will silence after so many minutes and not keep making noise. 

I guess the number one favorite feature of mine would be that I can set multiple timer's. I am always using that when cooking or washing clothes or making a cup of tea. :) I have looked at a number of alarm clocks and most of them have one thing in common, you can only set one timer at a time.

As for the colors I think a dark blue background would be cool. Just something a little bit lighter than black. Let me know what you think?

**Comment by mariobrostech** [comment]
@qw123wh A completely black theme for devices with AMOLED displays would be at the top of my list. An option in the app's settings with a selection for Light, Dark, and Black/AMOLED themes (and an option to follow the system theme for newer versions of Android) would be fantastic, if you could make that work!

**Comment by ghost** [comment]
closing
